var OX_f3f5eaff = '';
OX_f3f5eaff += "<"+"style>\n";
OX_f3f5eaff += "@import url(\'https://fonts.googleapis.com/css?family=Roboto\');\n";
OX_f3f5eaff += ".outer-frame {\n";
OX_f3f5eaff += "border: 1px solid #c3c3c3;\n";
OX_f3f5eaff += "width: 725px;\n";
OX_f3f5eaff += "height: 323px;\n";
OX_f3f5eaff += "}\n";
OX_f3f5eaff += ".upper-box {\n";
OX_f3f5eaff += "height: 65%;\n";
OX_f3f5eaff += "background-color: #2C2C54;\n";
OX_f3f5eaff += "padding: 30px 0px 0px 25px;\n";
OX_f3f5eaff += "}\n";
OX_f3f5eaff += ".logo {\n";
OX_f3f5eaff += "padding-bottom: 6px;\n";
OX_f3f5eaff += "}\n";
OX_f3f5eaff += ".header-text {\n";
OX_f3f5eaff += "font-family: \'Roboto\', sans-serif;\n";
OX_f3f5eaff += "font-size: 24px;\n";
OX_f3f5eaff += "color: #CECEF4;\n";
OX_f3f5eaff += "}\n";
OX_f3f5eaff += ".form-style {\n";
OX_f3f5eaff += "margin:0;\n";
OX_f3f5eaff += "padding:0;\n";
OX_f3f5eaff += "color:#000;\n";
OX_f3f5eaff += "font-size:18px;\n";
OX_f3f5eaff += "}\n";
OX_f3f5eaff += ".field {\n";
OX_f3f5eaff += "border:1px solid #000;\n";
OX_f3f5eaff += "width: 70%;\n";
OX_f3f5eaff += "color:#989898;\n";
OX_f3f5eaff += "padding:13px 8px;\n";
OX_f3f5eaff += "font-size:16px;\n";
OX_f3f5eaff += "}\n";
OX_f3f5eaff += ".button {\n";
OX_f3f5eaff += "font-family: \'Roboto\', sans-serif;\n";
OX_f3f5eaff += "font-weight:bold;\n";
OX_f3f5eaff += "color:#ffffff;\n";
OX_f3f5eaff += "width: 23%;\n";
OX_f3f5eaff += "height:45px;\n";
OX_f3f5eaff += "background-image: linear-gradient(#EC6A00, #D35F01);\n";
OX_f3f5eaff += "border: none;\n";
OX_f3f5eaff += "cursor:pointer;\n";
OX_f3f5eaff += "font-size:20px;\n";
OX_f3f5eaff += "vertical-align: middle;\n";
OX_f3f5eaff += "}\n";
OX_f3f5eaff += ".lower-box {\n";
OX_f3f5eaff += "height: 35%;\n";
OX_f3f5eaff += "padding: 10px;\n";
OX_f3f5eaff += "}\n";
OX_f3f5eaff += "<"+"/style>\n";
OX_f3f5eaff += "<"+"div class=\"outer-frame\">\n";
OX_f3f5eaff += "<"+"div class=\"upper-box\">\n";
OX_f3f5eaff += "<"+"div class=\"logo\">\n";
OX_f3f5eaff += "<"+"img src=\"//images.ads.supplyframe.com/AdOps/logos/fc-white-color.png\" alt=\"Findchips\">\n";
OX_f3f5eaff += "<"+"/div>\n";
OX_f3f5eaff += "<"+"div class=\"header-text\">\n";
OX_f3f5eaff += "<"+"p>Find price and inventory from the leading distributors:<"+"/p>\n";
OX_f3f5eaff += "<"+"/div>\n";
OX_f3f5eaff += "<"+"div class=\"search-field\">\n";
OX_f3f5eaff += "<"+"form  action=\'https://ads.supplyframe.com/openads/www/delivery/ck.php\' method=\'GET\' name=\"f\"  class=\"form-style\" target=\'_blank\'>\n";
OX_f3f5eaff += "<"+"input class=\"field\" name=\"part\" max_length=\"80\" type=\"text\" value=\"VS1838\" onfocus=\"if(this.value==\'VS1838\')this.value=\'\';\" onblur=\"if(this.value==\'\')this.value=\'VS1838\';\" />\n";
OX_f3f5eaff += "<"+"input type=\"submit\" value=\"FIND PARTS\" class=\"button\">\n";
OX_f3f5eaff += "<"+"input type=\'hidden\' name=\'oaparams\' value=\'2__bannerid=217024__zoneid=265__cb=d1bd927d9c__oadest=%2F%2Fanalytics.supplyframe.com%2Ftrackingservlet%2Ftrack%2F%3Faction%3DadClick%26value1%3D%252FElectronic%2BComponents%26value2%3D217024%26value3%3D3%26zone%3D265%26extra%3Dquery%3DVS1838%7Ccontextualmatch%3Dnolimitation%7Clivetax%3D2%7Ccookietax%3D413%2C1633244%7Cectime%3D{ectime}%7Cecstatus%3D{ecstatus}%7Cmanufacturer%3D{manufacturer_enc}%7Cpart_number%3D{part_number_enc}%7Ccb%3Dd1bd927d9c%7Ch_value%3D2d14c1e98af6fed41585580089%7Ch_crc%3D2485905944%7Cgeo%3Dus%7Ccnt%3Dna%7Cbp%3D1%7Cbpf%3D0%7Ccp%3D0%7Ch_i%3Dy%7Cgcl%3D%7Cgclsrc%3D%7Cgclts%3D%26zone%3D265%26url%3Dhttp%253A%252F%252Fwww.findchips.com%252F%253Futm_source%253Dsfmedia%2526utm_medium%253Dipo%2526utm_campaign%253Dgrowfindchipsusers%2526utm_content%253Dpurplefindparts001\'><"+"/form>\n";
OX_f3f5eaff += "<"+"/div>\n";
OX_f3f5eaff += "<"+"/div>\n";
OX_f3f5eaff += "<"+"div class=\"lower-box\">\n";
OX_f3f5eaff += "<"+"div class=\"company-logos\">\n";
OX_f3f5eaff += "<"+"img src=\"//images.ads.supplyframe.com/AdOps/logos/brand-logos-interactive2.gif\">\n";
OX_f3f5eaff += "<"+"/div>\n";
OX_f3f5eaff += "<"+"/div>\n";
OX_f3f5eaff += "<"+"/div><"+"div id=\'beacon_d1bd927d9c\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.supplyframe.com/openads/www/delivery/lg.php?bannerid=217024&amp;campaignid=415&amp;zoneid=265&amp;loc=1&amp;referer=https%3A%2F%2Fsearch.supplyframe.com%2Fpartner%2F15%2Fsearch%2FVS1838&amp;cb=d1bd927d9c\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"script type=\"text/javascript\">\n";
OX_f3f5eaff += "var _gaq = _gaq || [];\n";
OX_f3f5eaff += "_gaq.push([\'_setAccount\', \'UA-81436-2\']);\n";
OX_f3f5eaff += "_gaq.push([\'_trackPageview\']);\n";
OX_f3f5eaff += "_gaq.push([\'_setCampNameKey\', \'datasheet4u_ads_265\']);\n";
OX_f3f5eaff += "(function() {\n";
OX_f3f5eaff += "var ga = document.createElement(\'script\'); ga.type = \'text/javascript\'; ga.async = true;\n";
OX_f3f5eaff += "ga.src = (\'https:\' == document.location.protocol ? \'https://ssl\' : \'http://www\') + \'.google-analytics.com/ga.js\';\n";
OX_f3f5eaff += "var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(ga, s);\n";
OX_f3f5eaff += "})();\n";
OX_f3f5eaff += "<"+"/script>\n";
OX_f3f5eaff += "<"+"script type=\"text/javascript\">\n";
OX_f3f5eaff += "(function() {\n";
OX_f3f5eaff += "window._pa = window._pa || {};\n";
OX_f3f5eaff += "var pa = document.createElement(\'script\'); pa.type = \'text/javascript\'; pa.async = true;\n";
OX_f3f5eaff += "pa.src = (\'https:\' == document.location.protocol ? \'https:\' : \'http:\') + \"//tag.perfectaudience.com/serve/5266e87c5dd5ca039c00002d.js\";\n";
OX_f3f5eaff += "var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(pa, s);\n";
OX_f3f5eaff += "})();\n";
OX_f3f5eaff += "window.onload=function(){\n";
OX_f3f5eaff += "_pa.track(\'category_2\');\n";
OX_f3f5eaff += "_pa.track(\'zone_265\');\n";
OX_f3f5eaff += "if (\'us\'!=\'cn\') {\n";
OX_f3f5eaff += "_pa.track(\'geo_notChina\');\n";
OX_f3f5eaff += "} else {\n";
OX_f3f5eaff += "_pa.track(\'geo_isChina\');\n";
OX_f3f5eaff += "}\n";
OX_f3f5eaff += "}\n";
OX_f3f5eaff += "<"+"/script>\n";
OX_f3f5eaff += "<"+"script type=\"text/javascript\" src=\"//ads.supplyframe.com/openads/www/delivery/fc.php?script=SupplyFrame:front:industry-tag&rand=d1bd927d9c\"><"+"/script><"+"img src=\'//analytics.supplyframe.com/trackingservlet/impression/?action=adImpression&amp;value1=%2FElectronic+Components&amp;value2=217024&amp;value3=3&amp;extra=query=VS1838|contextualmatch=nolimitation|livetax=2|cookietax=413,1633244|ectime={ectime}|ecstatus={ecstatus}|manufacturer={manufacturer_enc}|part_number={part_number_enc}|cb=d1bd927d9c|h_value=2d14c1e98af6fed41585580089|h_crc=2485905944|geo=us|cnt=na|bp=1|bpf=0|cp=0|h_i=y|gcl=|gclsrc=|gclts=&amp;zone=265\' width=\'0\' height=\'0\' alt=\'\' style=\'display:none\' />\n";
document.write(OX_f3f5eaff);
